name: dvgo-legacy
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - numpy
  - scipy
  - tqdm
  - imageio
  - imageio-ffmpeg
  - opencv
  - ninja
  - einops
  - tensorboard
  - setuptools
  - wheel
  - pip:
      - lpips
      - mmcv-lite
      - mmengine
      - torch_efficient_distloss
